# Generated by Django 3.2.3 on 2021-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masv', models.CharField(max_length=15)),
                ('hoten', models.CharField(max_length=50)),
                ('khoa', models.CharField(max_length=50)),
                ('gioitinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], max_length=3)),
            ],
        ),
    ]
