# Generated by Django 3.2.3 on 2021-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gioitinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3),
        ),
    ]
